### ISSUE TITLE
Building local development environment

### ISSUE THREAD

**Issue by taniwhy** [taniwhy/blog#1]
## Overview

Build a local development environment.

## Task

- [x] Create a skeleton of the application
- [x] Create a Docker file for the application
- [x] Configure GitHub settings
